config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }  
  resources :users, only: [:show]
  resources :microposts, only: [:index, :create]
  resources :followings, only: [:create]
  resources :following_user_microposts, only: %i[index]
  resources :likings, only: [:create]
  resources :liking_users, only: %i[index]
  resources :comments, only: %i[index create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :micropost
  belongs_to :user
  validates :micropost_id, presence: true
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140}  
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :user
  belongs_to :following_user, class_name: 'User'
  validates :user, presence: true
  validates :following_user, presence: true
  validates :following_user, uniqueness: { scope: :user }
end

app/models/liking.rb
class Liking < ApplicationRecord
  belongs_to :micropost
  belongs_to :user
  validates :user, uniqueness: { scope: :micropost}
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :likings
  has_many :users, through: :likings
  has_many :comments
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140}
  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts
  has_many :followings
  has_many :following_users, through: :followings
  has_many :comments
  validates :name, presence: true, length: {maximum: 20}, format: {with: /\A[a-zA-Z]+\z/}
  validates :profile, length: {maximum: 200}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # allow users to update their accounts without passwords
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth, if: :production?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit :sign_up, 
        keys: [ :email, :name, :password, :password_confirmation ]
      devise_parameter_sanitizer.permit :account_update, 
        keys: [ :email, :name, :profile, :url, :password, :password_confirmation ]
      devise_parameter_sanitizer.permit :sign_in, 
        keys: [ :email, :password]
    end

  private

    def production?
      Rails.env.production?
    end

    def basic_auth
      authenticate_or_request_with_http_basic do |name, password|
        name == ENV['BASIC_AUTH_NAME'] && password == ENV['BASIC_AUTH_PASSWORD']
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def index
    if user_signed_in?
      @comment = current_user.comments.build
      @following_users = current_user.following_users
    end
    @micropost = Micropost.find(params[:micropost_id])
    @comments = @micropost.comments.paginate(page: params[:page])
  end

  def create
    comment = Comment.new(comment_params)
    if comment.save
      flash[:success] = "コメントの書き込みに成功しました"
      CommentNotifierMailer.send_comment_email(comment.micropost.user, comment.micropost_id).deliver
    else
      flash[:failure] = "コメントの書き込みに失敗しました"
    end
    redirect_to comments_path(micropost_id: comment.micropost_id)
  end

  private
    def comment_params
      params.require(:comment).permit(:user_id, :micropost_id, :content)
    end
end

app/controllers/following_user_microposts_controller.rb
class FollowingUserMicropostsController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @following_users = current_user.following_users
    @microposts = Micropost.preload(%i[user users]).where(user: @following_users).order(created_at: :desc).paginate(page: params[:page])
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    following_params = params.require(:following).permit(:following_user_id)
    following = current_user.followings.build(following_params)
    if following.save
      flash[:success] = "フォローに成功しました"
    else
      flash[:failure] = "フォローに失敗しました"
    end
    redirect_to root_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      @micropost = current_user.microposts.build
      @following_users = current_user.following_users
    end
    @microposts = Micropost.preload(%i[user users]).order(created_at: :desc).paginate(page: params[:page])
  end
end

app/controllers/liking_users_controller.rb
class LikingUsersController < ApplicationController
  def index
    micropost = Micropost.find(params[:micropost_id])
    @liking_users = micropost.users
  end
end

app/controllers/likings_controller.rb
class LikingsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    liking_params = params.require(:liking).permit(:micropost_id, :user_id)
    liking = Liking.new(liking_params)
    if liking.save
      flash[:success] = "いいねに成功しました"
    else
      flash[:failure] = "いいねに失敗しました"
    end

    previous_path = Rails.application.routes.recognize_path(request.referer)
    if previous_path[:controller] == 'home' && previous_path[:action] == 'index'
      redirect_to root_url
    elsif previous_path[:controller] == 'following_user_microposts' && previous_path[:action] == 'index'
      redirect_to following_user_microposts_path
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :index]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      redirect_to new_user_session_url
    end

  end

  def index
    @microposts = current_user.microposts.order(created_at: :desc).paginate(page: params[:page])
  end

  private
    def micropost_params
      params.require(:micropost).permit(:content, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/following_user_microposts_helper.rb
module FollowingUserMicropostsHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/liking_users_helper.rb
module LikingUsersHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.haml
%div{class: "row", id: "micropost-#{@micropost.id}"}
  %div.card
    %div.card-header
      %div.btn-toolbar
        %h4.btn-group.mr-2= link_to @micropost.user.name, user_path(@micropost.user)
        - if user_signed_in? && current_user.id != @micropost.user.id && @following_users.exclude?(@micropost.user)
          = form_with(model: current_user.followings.build(following_user: @micropost.user), remote: true) do |f|
            %div= f.hidden_field :following_user_id
            = f.submit "Follow", class: "btn-group mr-2 btn btn-primary btn-sm"
        - if user_signed_in? && @micropost.users.exclude?(current_user)
          = form_with(model: @micropost.likings.build(micropost: @micropost, user: current_user), remote: true) do |f|
            %div= f.hidden_field :micropost_id
            %div= f.hidden_field :user_id
            = f.submit "Liking", class: "btn-group mr-2 btn btn-primary btn-sm"
      %h6
        = link_to "#{@micropost.likings.count} liking user".pluralize(@micropost.likings.count), liking_users_path(micropost_id: @micropost.id)
        = link_to ", #{@micropost.comments.count} comments".pluralize(@micropost.comments.count), comments_path(micropost_id: @micropost.id)
        = ", Posted #{l @micropost.created_at}"
    %div.card-body
      %div.card-text
        %h4= @micropost.content
- if user_signed_in?
  %div.form-group
    = form_with(model: current_user.comments.build(micropost: @micropost, user: current_user), remote: true) do |f|
      %div.field= f.text_area :content, placeholder: "Compose new comment...", class: "form-control"
      %div= f.hidden_field :micropost_id
      %div= f.hidden_field :user_id
      = f.submit "Comment", class: "btn btn-primary btn-block"
- if @comments.any?
  %h2 Comments
  %ul.list-group
  - @comments.each do |comment|
    %li.list-group-item
      %ul.list-group.list-group-horizontal
        %li.list-group-item= link_to comment.user.name, user_path(comment.user)
        %li.list-group-item= comment.content
    = will_paginate @comments, previous_label: '&lt 前へ', next_label: '次へ &gt'

app/views/following_user_microposts/index.html.haml
%h1 Following user timeline
- if @microposts.any?
  - @microposts.each do |micropost|
    = render 'microposts/micropost', micropost: micropost, following_users: @following_users
  = will_paginate @microposts, previous_label: '&lt 前へ', next_label: '次へ &gt', params: { controller: :following_user_microposts, action: :index }

app/views/home/index.html.haml
- if user_signed_in?
  = render 'shared/micropost_form'
= render 'shared/microposts'

app/views/liking_users/index.html.haml
%h1 Liking users to the micropost
- if @liking_users.any?
  - @liking_users.each do |user|
    %div{class: "row", id: "user-#{user.id}"}
      %div.card
        %div.card-header
          %h4= link_to user.name, user_path(user)
        %div.card-body
          %div.card-text
            %h4= user.profile